# Site settings
title: Natalia Berdys
hello: hi, i'm natalie!
email: hello@batalia.me
url: https://www.batalia.me
description: "Natalia Berdys - iOS App Developer, Game Developer, Designer & Speaker. Creator of #1 apps worldwide, WWDC speaker, Mobile Development expert. Based in Ottawa, Canada."
skills: "iOS App / Game Developer - Designer - Speaker"
meta_author: Berdys Natalia

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

contact: static

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 7A6B95 #80B3FF
  primary-rgb: "122,107,149" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  social: follow me

# Can add more here
social:
  - title: twitter
    url: http://twitter.com/batalia
  - title: stack-overflow
    url: http://stackoverflow.com/users/1703254/batalia?tab=profile

# Build settings
markdown: kramdown
permalink: pretty
